---
- name: Provision and configure the server
  hosts: all
  become: yes

  vars:
    mysql_root_unix_socket: /var/run/mysqld/mysqld.sock 
    login_unix_socket: "{{ mysql_root_unix_socket }}"
    login_user: "{{ MYSQL_USER }}"
    login_password: "{{ MYSQL_PASSWORD }}"
    
  tasks:
    - name: Update packages
      dnf:
        name: '*'
        state: latest

    - name: Install required packages
      dnf:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - nginx
        - awscli
        - python3-pip

    - name: Install AWS CLI using pip
      pip:
        name: awscli
        executable: pip3

    - name: Install pymysql using pip
      pip:
        name: pymysql
        executable: pip3

    - name: Run MariaDB installation tasks
      include_tasks: install_mysql.yml
